### PR TITLE
PROTECT fixes.

### PR DESCRIPTION
**Pull request by kalibera**

### CODE REVIEW

**Comment by s-u** [comment]
@kalibera thanks, but can you explain why you think those are needed? There is no R API code involved in that region.

**Comment by kalibera** [comment]
This based on rchk reports  (https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/RSclient.out):

```
 Suspicious call (two or more unprotected arguments) to Rf_setAttrib at RS_collect RSclient/src/cli.c:971
```

here the call to install("index") can trigger GC and destroy the object allocated by ScalarInteger

```
Function RS_assign
  [UP] unprotected variable res while calling allocating function rsc_read RSclient/src/cli.c:1018

Function RS_authkey
  [UP] unprotected variable res while calling allocating function rsc_read RSclient/src/cli.c:1139

Function RS_eval
  [UP] unprotected variable res while calling allocating function rsc_read RSclient/src/cli.c:907
```

In these calls, rsc_read may at least call into REprintf() via rsc_abort, so R API. 

```
Function RS_eval_qap
  [UP] unprotected variable outv while calling allocating function QAP_storeSEXP RSclient/src/cli.c:837
  [UP] unprotected variable outv while calling allocating function rsc_write RSclient/src/cli.c:852
  [UP] unprotected variable res while calling allocating function rsc_read RSclient/src/cli.c:862
```

Here in addition rsc_write may also call to rsc_abort via rsc_flush. I don't immediately see how QAP_storeSEXP calls into R API

**Comment by s-u** [comment]
Ok, got it, so they are false-positives, because the value is not used after that point, but the check tools have no way of knowing that. (It is still useful since manual inspection for the code revealed some unrelated bugs in the abort handling).

**Comment by kalibera** [comment]
The first case with setAttrib seems as a true positive to me.

The cases calling just once rsc_abort, yes, if the corrupted value is never used after REprintf, then it will be harmless, but it is beyond what the tool can analyze It supports code paths with long-jumps, and it looks at whether the variables are still used, but not in such complicated ways that would be needed to understand this code.

The third case which involves calls to QAP_storeSEXP, rsc_write and rsc_read seems also as true positive to me. The return value of the first rsc_write is not checked, so the data may be corrupted but the code still continues. The result of QAP_storeSEXP is not checked, either (QAP_storeSEXP also calls REprintf). It would be probably hard to run into these in practice, but technically they seem as true positives.

**Comment by s-u** [comment]
Thanks, I think those should be now fixed

**Pull request closed without merging**
